/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedProfileRouteImport } from './routes/_authed.profile'
import { Route as AuthedMessagesRouteImport } from './routes/_authed.messages'
import { Route as AuthedFeedRouteImport } from './routes/_authed.feed'
import { Route as AuthedCreateRouteImport } from './routes/_authed.create'
import { Route as AuthedListingIdRouteImport } from './routes/_authed.listing.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedProfileRoute = AuthedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMessagesRoute = AuthedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedFeedRoute = AuthedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCreateRoute = AuthedCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedListingIdRoute = AuthedListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/create': typeof AuthedCreateRoute
  '/feed': typeof AuthedFeedRoute
  '/messages': typeof AuthedMessagesRoute
  '/profile': typeof AuthedProfileRoute
  '/listing/$id': typeof AuthedListingIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/create': typeof AuthedCreateRoute
  '/feed': typeof AuthedFeedRoute
  '/messages': typeof AuthedMessagesRoute
  '/profile': typeof AuthedProfileRoute
  '/listing/$id': typeof AuthedListingIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/create': typeof AuthedCreateRoute
  '/_authed/feed': typeof AuthedFeedRoute
  '/_authed/messages': typeof AuthedMessagesRoute
  '/_authed/profile': typeof AuthedProfileRoute
  '/_authed/listing/$id': typeof AuthedListingIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/create'
    | '/feed'
    | '/messages'
    | '/profile'
    | '/listing/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/create'
    | '/feed'
    | '/messages'
    | '/profile'
    | '/listing/$id'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/signup'
    | '/_authed/create'
    | '/_authed/feed'
    | '/_authed/messages'
    | '/_authed/profile'
    | '/_authed/listing/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/profile': {
      id: '/_authed/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthedProfileRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/messages': {
      id: '/_authed/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthedMessagesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/feed': {
      id: '/_authed/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthedFeedRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/create': {
      id: '/_authed/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof AuthedCreateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/listing/$id': {
      id: '/_authed/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof AuthedListingIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedCreateRoute: typeof AuthedCreateRoute
  AuthedFeedRoute: typeof AuthedFeedRoute
  AuthedMessagesRoute: typeof AuthedMessagesRoute
  AuthedProfileRoute: typeof AuthedProfileRoute
  AuthedListingIdRoute: typeof AuthedListingIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCreateRoute: AuthedCreateRoute,
  AuthedFeedRoute: AuthedFeedRoute,
  AuthedMessagesRoute: AuthedMessagesRoute,
  AuthedProfileRoute: AuthedProfileRoute,
  AuthedListingIdRoute: AuthedListingIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
